spring:
  application:
    name: Expense Tracker

spring:
  datasource:
    url: jdbc:h2:file:./data/testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080
